### PR TITLE
update readme.md

### PR DESCRIPTION
**Pull request by pFernbach**
- add a step to install hpp-template-corba (required)
- fix link to hpp and stonneau repo instead of anna-seppela repo
- fix cmake install path

### CODE REVIEW

**Comment by jmirabel** [comment]
`hpp-template-corba` should be installed automatically when installing HPP.

**Comment by jmirabel** [comment]
By the way, it shouldn't be hard to add `hpp-rbprm` to the HPP Makefile.

**Comment by pFernbach** [comment]
`hpp-template-corba` is in the makefile but it will not be installed with the `make all`.
I guess the best option is to add affordance and rbprm in the HPP makefile and change the install instruction for this 2 package ?

**Comment by jmirabel** [comment]
For each package, you must define the variables:
```Makefile
<pkg-name>_branch=master
<pkg-name>_repository=${HPP_REPO}
```
and declare the dependencies:
```Makefile
<pkg-name>.configure.dep: dependency1.install dependency2.install <pkg-name>.checkout
```
This will set up everything that the target `<pkg-name>.install` needs.

PS: I thought `hpp-template-corba` was a dependency of `hpp-corbaserver`, sorry...

**Comment by jmirabel** [comment]
I close this pull-request since it is very old. Please, reopen if needed.

**Pull request closed without merging**
